lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_5/urls.py
from django.conf.urls import url
from .views import index, add_todo

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_todo', add_todo, name='add_todo'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url='lab-2/', permanent=True), name='go-to-lab-2'),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
]

lab_5/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=27)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

lab_5/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Please fill this input',
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Title'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Description'
    }

    title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

lab_5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):    
    response['author'] = "" #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    html = 'lab_5/lab_5.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['title'] = request.POST['title']
        response['description'] = request.POST['description']
        todo = Todo(title=response['title'],description=response['description'])
        todo.save()
        messages.add_message(request, messages.SUCCESS, 'Berhasil menambahkan Todo')
        return HttpResponseRedirect('/lab-5/')
    else:
        return HttpResponseRedirect('/lab-5/')

lab_5/templates/lab_5/lab_5.html
{% extends "lab_5/layout/base.html" %}

{% block content %}
<h1 class="main-title">TODOLIST</h1>
<hr/>
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} class="alert alert-success alert-dismissable fade in"{% endif %}>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'lab-5:add_todo' %}">
            <h2>Input Todo</h2>
            {% csrf_token %}
            {{ todo_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">My List</h2>
        <div class="flex">
            {% if todo %}
                {% for data in todo %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-title">
                                {{data.title}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="to-do-list-description">
                                {{data.description}}
                            </div>
                            <div class="to-do-list-delete">
                                <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> There are no TODO data.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

lab_5/templates/lab_5/tutorial.html
{% load staticfiles %}
<html>
    <head>
        <title>Tutorial CSS Yay</title>
        <link rel="stylesheet" href="{% static 'css/tutorial.css' %}">
    </head>
    <body>
        <div id="header">
            <h1>Tutorial CSS Yay</h1>
        </div>
        <div id="main">
            <div class="content_section">
                <p class="date">published: 31 September 2017</p>
                <h2><a href="">My CSS tutorial</a></h2>
                <p id="content_1">Yay, this is an easy tutorial!</p>
            </div>
            <div class="content_section">
                <p class="date ">published: 32 September 2017</p>
                <h2><a href="">Your CSS tutorial</a></h2>
                <p id="content_2">Yay this is an easy tutorial!</p>
            </div>
            <div class="content_section">
                <p>published: 33 September 2017</p>
                <h2><a href="">CSS Tutorial for all</a></h2>
                <p id="content_3">Yay this tutorial is not hard!</p>
            </div>
        </div>

    </body>
</html>